COMMERCE-7204 Missing upgrade in 205a82f5, see error:
java.lang.Exception:  ## ## 4 Liferay Exceptions were thrown ##  LIFERAY_ERROR: Key column 'ctCollectionId' doesn't exist in table: create index IX_42A41BCC on CPDefinitionLocalization (CPDefinitionId, ctCollectionId); LIFERAY_ERROR: Key column 'ctCollectionId' doesn't exist in table: create unique index IX_CB617913 on CPDefinitionLocalization (CPDefinitionId, languageId, ctCollectionId); LIFERAY_ERROR: Unknown column 'CPDefinitionLocalization.ctCollectionId' in 'where clause' LIFERAY_ERROR: Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, EXCEPTIONS_MAX_SIZE=0, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@36ee6575, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener}}
Stacktrace
java.lang.Exception:

LIFERAY_ERROR: Key column 'ctCollectionId' doesn't exist in table: create index IX_42A41BCC on CPDefinitionLocalization (CPDefinitionId, ctCollectionId);
LIFERAY_ERROR: Key column 'ctCollectionId' doesn't exist in table: create unique index IX_CB617913 on CPDefinitionLocalization (CPDefinitionId, languageId, ctCollectionId);
LIFERAY_ERROR: Unknown column 'CPDefinitionLocalization.ctCollectionId' in 'where clause'
LIFERAY_ERROR: Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, EXCEPTIONS_MAX_SIZE=0, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@36ee6575, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.commerce.product.definitions.web.internal.messaging.CheckCPDefinitionMessageListener}}