LPS-137330 I got errors with these 2 tests. please fix. Thx! See log:
com.liferay.object.admin.rest.resource.v1_0.test.ObjectFieldResourceTest > testPatchObjectField FAILED
    java.lang.AssertionError: {"id": 1476461071567353635, "indexed": false, "indexedAsKeyword": false, "indexedLanguageId": "5zjtfffx", "label": {"en_US": "Arnx03ezu"}, "name": "arnx03ezu", "required": false, "type": "String"} does not equal {"id": 42195, "indexed": false, "indexedAsKeyword": false, "indexedLanguageId": "5zjtfffx", "name": "awkbimrsb", "required": false, "type": "String"}
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectFieldResourceTestCase.assertEquals(BaseObjectFieldResourceTestCase.java:421)
    	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectFieldResourceTestCase.testPatchObjectField(BaseObjectFieldResourceTestCase.java:368)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:748)

com.liferay.object.admin.rest.resource.v1_0.test.ObjectFieldResourceTest > testPostObjectDefinitionObjectField STARTED

com.liferay.object.admin.rest.resource.v1_0.test.ObjectFieldResourceTest > testPostObjectDefinitionObjectField PASSED

com.liferay.object.admin.rest.resource.v1_0.test.ObjectFieldResourceTest > testPutObjectField STARTED

com.liferay.object.admin.rest.resource.v1_0.test.ObjectFieldResourceTest > testPutObjectField FAILED
    java.lang.AssertionError: {"id": 4595782363684965648, "indexed": true, "indexedAsKeyword": false, "indexedLanguageId": "llxquyg3", "label": {"en_US": "Aupdj14ax"}, "name": "aupdj14ax", "required": false, "type": "String"} does not equal {"id": 42223, "indexed": true, "indexedAsKeyword": false, "indexedLanguageId": "llxquyg3", "name": "a87iajxfx", "required": false, "type": "String"}
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectFieldResourceTestCase.assertEquals(BaseObjectFieldResourceTestCase.java:421)
    	at com.liferay.object.admin.rest.resource.v1_0.test.BaseObjectFieldResourceTestCase.testPutObjectField(BaseObjectFieldResourceTestCase.java:388)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Met